### ISSUE TITLE
EC518 : BluetoothBleCheck - Add descriptions for terms Ble & Bc and optimise rule

### ISSUE THREAD

**Issue by 47tibo** [green-code-initiative/ecoCode-kotlin-android#2]
### current behavior

1) `Ble` & `Bc` terms are used in variables.

2) `Ble` & `Bc` checks are tightly coupled : 

```
if (bleImports.isNotEmpty() || bcImports.isNotEmpty()) {
            if (bleImports.isNotEmpty()) {
                bleImports.forEach {
                    it.importedReference?.let { data?.reportIssue(it, GOOD_PRACTICE_MESSAGE) }
                }
            } else {
                bcImports.forEach {
                    it.importedReference?.let { data?.reportIssue(it, ERROR_MESSAGE) }
                }
            }
        }
```

### enhancement suggested

1) `Ble` & `Bc` terms are technical terms unknown to junior android developers. Their usage is now a standard, so it won't be a good idea to rename all their usage in the codebase to `bluetoothLowEnergy` & `bluetoothClassic`.
So a good compromise will be to add 2 comments at the top of the file : 

 ```
// ble stands for "Bluetooth Low Energy"
// bc stands for "Bluetooth Classic"
```

2)
Their use in the codebase are totally independent : we can import the Ble without the Bc and inversely import the Bc without using the Ble. It is also possible to use both of them (really bad practice, but still, possible).
So we can make them totally independent, and remove conditional checks : 

```
bleImports.forEach { import ->
    import.importedReference?.let { data?.reportIssue(it, GOOD_PRACTICE_MESSAGE) }
}

bcImports.forEach { import ->
    import.importedReference?.let { data?.reportIssue(it, ERROR_MESSAGE) }
}
```

**Comment by glalloue** [comment]
I completely agree with you on point 1)

and also with point 2)

**Comment by 47tibo** [comment]
Thanks @glalloue 🙂

@Jberque are you ok with enhancement #1 ?
Concerning enhancement #2,  I think we can resume the conditional tree this way : 

![image](https://github.com/green-code-initiative/ecoCode-kotlin-android/assets/3033301/cb28a790-c82a-4631-941d-98d706984b38)

So the final enhancement will be : 

```
val hasBleImports = bleImports.isNotEmpty()
if (hasBleImports || bcImports.isNotEmpty()) {
  if (hasBleImports) {
    bleImports.forEach { import ->
        import.importedReference?.let { data?.reportIssue(it, GOOD_PRACTICE_MESSAGE) }
    }
  } else {
    bcImports.forEach { import ->
        import.importedReference?.let { data?.reportIssue(it, ERROR_MESSAGE) }
    }
  }
}
```

What do you think ?

**Comment by glalloue** [comment]
I let @Jberque confirm with you after your discussions on this subject
Maybe you can notify him on slack about it to be sure I saw your message

**Comment by Jberque** [comment]
@jhertout what do you think of the point 2. 

it will replace : 

` if (bleImports.isNotEmpty() || bcImports.isNotEmpty()) {
            if (bleImports.isNotEmpty()) {
                bleImports.forEach {
                    it.importedReference?.let { data?.reportIssue(it, GOOD_PRACTICE_MESSAGE) }
                }
            } else {
                bcImports.forEach {
                    it.importedReference?.let { data?.reportIssue(it, ERROR_MESSAGE) }
                }
            }
        }`
        
by that : 
        
`val hasBleImports = bleImports.isNotEmpty()
if (hasBleImports || bcImports.isNotEmpty()) {
  if (hasBleImports) {
    bleImports.forEach { import ->
        import.importedReference?.let { data?.reportIssue(it, GOOD_PRACTICE_MESSAGE) }
    }
  } else {
    bcImports.forEach { import ->
        import.importedReference?.let { data?.reportIssue(it, ERROR_MESSAGE) }
    }
  }
}
`

**Comment by 47tibo** [comment]
@jhertout thanks for your feedback.
@Jberque, following Robert Martin advices (in _Clean Code_ , "smells and heuristics"), more precisely the rules 

1) avoid duplication (G5)
2) be consistent (G11)
3) avoid negative conditionals (G29)

we can go with this implementation : 
```
val hasBleImports = bleImports.isNotEmpty()
val hasBcImports = bcImports.isNotEmpty()
if (hasBleImports || hasBcImports)
```

@Jberque if you're ok with that I can open a PR with this change 🙂
